# Generated by Django 4.2.3 on 2024-09-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("1", "First Semester"),
                            ("2", "Second Semester"),
                            ("3", "Third Semester"),
                            ("4", "Fourth Semester"),
                            ("5", "Fifth Semester"),
                            ("6", "Sixth Semester"),
                            ("7", "Seventh Semester"),
                            ("8", "Eighth Semester"),
                        ],
                        max_length=1,
                    ),
                ),
                ("pdf_file", models.FileField(upload_to="notes_pdfs/")),
            ],
        ),
    ]
