# Generated by Django 4.2.3 on 2024-09-14 12:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0002_video"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Video",
        ),
    ]
